name: Selenium Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Selenium script
      run: |
        python selenium_test.py || echo "Selenium tests failed"
        if [ $? -ne 0 ]; then
          echo "Selenium tests failed, sending email notification"
          echo "Selenium tests failed" | mail -s "Selenium Tests Failed" -a "From: Your Name <aashishjangir1123@gmail.com>" -a "Content-Type: text/html" your@gmail.com --smtp-address smtp.gmail.com --smtp-user your@gmail.com --smtp-password ${{ secrets.GMAIL_PASSWORD }}
          exit 1
        fi
